// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awuwllfvzvfkzpfcxujk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dXdsbGZ2enZma3pwZmN4dWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjQ1MDEsImV4cCI6MjA3MTM0MDUwMX0.zn01RSW_1JtxvtfJfiijggkW5camRy34yrVuncwxAAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});